language: objective-c
osx_image: xcode7.0
script:
- xctool -workspace Example/Hokusai.xcworkspace -scheme Hokusai-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO clean build test


